### ISSUE TITLE
meson optional unit-tests

### ISSUE THREAD

**Issue by joelkraehemann** [gsequencer/community#1]
The tests should be optional to compile with meson. Might be there is a test runner, too.

**Comment by damaxi** [comment]
@joelkraehemann https://github.com/gsequencer/gsequencer/pull/46 I fixed it.

However during fix I discovered 2 more issues:
- there is missing dependency to ladspa (I haven't figured out how it is used) but it looks like it requires a special rules
- the next thing is dssa this library is quite obsolete and in addition its build sytem requires qt4 to build examples :(

Maybe we can talk later.

**Comment by joelkraehemann** [comment]
LADSPA and DSSI needs just a header file which is usually located here:

- /usr/include/ladspa.h
- /usr/include/dssi.h

You can build DSSI without Qt4.

**Comment by joelkraehemann** [comment]
#https://github.com/gsequencer/gsequencer/pull/46

thank you!
